services:
  - type: web
    name: tp-backend
    plan: free
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      
