services:
  - type: web
    name: tp-backend
    plan: free
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    buildFilter:
      paths:
        - backend/**

  - type: static
    name: ticket-please
    buildCommand: npm install && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - frontend/**
    rootDir: frontend
